version: "3.4"

networks:
  dev:
    driver: bridge

services:
  # api-app:
  #   container_name: app_services
  #   image: docker.io/library/api-image
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - ConnectionStrings__DefaultConnection=User Id=postgres;Password=bodqtr115;Server=app_db;Port=5432;Database=appDb;IntegratedSecurity=true;Pooling=true
  #     - ASPNETCORE_URLS=http://+:80
  #   networks:
  #     - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bodqtr115
      - POSTGRES_DB=appDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data: {}
